const jobs =   [
  
  
    {
      "id": 1,
      "company": "ABC Ltd",
      "position": "Software Engineer",
      "title": "Full Stack Developer",
      "description": "Develop web applications using modern technologies.",
      "type": "Full-time",
      "date_posted": "2023-09-14",
      "location": "Bangor",
      "postcode": "LL57 1EG",
      "skills_required": ["JavaScript", "React", "Node.js"],
      "salary_range": "£60,000 - £80,000",
      "experience_level": "Mid-level",
      "latitude": 53.224842,
      "longitude": -4.115264
    },
    {
      "id": 2,
      "company": "XYZ Inc",
      "position": "Data Analyst",
      "title": "Data Analyst",
      "description": "Analyze and interpret data for business insights.",
      "type": "Part-time",
      "date_posted": "2023-09-15",
      "location": "London",
      "postcode": "E1 6AN",
      "skills_required": ["Data Analysis", "SQL", "Excel"],
      "salary_range": "£55,000 - £75,000",
      "experience_level": "Entry-level",
      "latitude": 51.518852,
      "longitude": -0.078510
    },
    {
      "id": 3,
      "company": "Tech Solutions",
      "position": "UX Designer",
      "title": "Senior UX Designer",
      "description": "Lead the design of user-friendly interfaces.",
      "type": "Full-time",
      "date_posted": "2023-09-16",
      "location": "Bangor",
      "postcode": "LL57 1US",
      "skills_required": ["UX/UI Design", "Wireframing", "Prototyping"],
      "salary_range": "£70,000 - £90,000",
      "experience_level": "Senior",
    },
    {
      "id": 4,
      "company": "EcoTech Ltd",
      "position": "Environmental Scientist",
      "title": "Environmental Researcher",
      "description": "Study and analyze environmental data.",
      "type": "Contract",
      "date_posted": "2023-09-17",
      "location": "Manchester",
      "postcode": "M1 2EW",
      "skills_required": ["Environmental Science", "Data Analysis", "Fieldwork"],
      "salary_range": "£45,000 - £65,000",
      "experience_level": "Mid-level",
      "latitude": 53.478735,
      "longitude": -2.225385
    },
    {
      "id": 5,
      "company": "FinTech Solutions",
      "position": "Financial Analyst",
      "title": "Senior Financial Analyst",
      "description": "Analyze financial data and provide insights.",
      "type": "Full-time",
      "date_posted": "2023-09-18",
      "location": "Bangor",
      "postcode": "LL57 2AW",
      "skills_required": ["Financial Analysis", "Excel", "Budgeting"],
      "salary_range": "£50,000 - £70,000",
      "experience_level": "Senior",
    },
    {
      "id": 6,
      "company": "HealthCare Ltd",
      "position": "Nurse",
      "title": "Registered Nurse",
      "description": "Provide patient care and medical assistance.",
      "type": "Full-time",
      "date_posted": "2023-09-19",
      "location": "Bangor",
      "postcode": "LL57 2PS",
      "skills_required": ["Nursing", "Patient Care", "Medical Knowledge"],
      "salary_range": "£60,000 - £80,000",
      "experience_level": "Mid-level",
      "latitude": 53.208470,
      "longitude": -4.165848
    },
    {
      "id": 7,
      "company": "Tech Innovators",
      "position": "Software Engineer",
      "title": "Front-end Developer",
      "description": "Create interactive and responsive web interfaces.",
      "type": "Full-time",
      "date_posted": "2023-09-20",
      "location": "London",
      "postcode": "E1 5RU",
      "skills_required": ["HTML", "CSS", "JavaScript"],
      "salary_range": "£80,000 - £100,000",
      "experience_level": "Mid-level",
      "latitude": 51.522323,
      "longitude": -0.056868
    },
    {
      "id": 8,
      "company": "Green Energy Co.",
      "position": "Environmental Engineer",
      "title": "Renewable Energy Engineer",
      "description": "Design and implement renewable energy solutions.",
      "type": "Full-time",
      "date_posted": "2023-09-21",
      "location": "Manchester",
      "postcode": "M1 3GL",
      "skills_required": ["Renewable Energy", "Engineering", "Sustainability"],
      "salary_range": "£70,000 - £90,000",
      "experience_level": "Mid-level",
      "latitude": 53.477603,
      "longitude": -2.234163
    },
    {
      "id": 9,
      "company": "EduTech Solutions",
      "position": "Teacher",
      "title": "Mathematics Teacher",
      "description": "Educate and inspire students in mathematics.",
      "type": "Full-time",
      "date_posted": "2023-09-22",
      "location": "London",
      "postcode": "E1 6BD",
      "skills_required": ["Teaching", "Mathematics", "Classroom Management"],
      "salary_range": "£55,000 - £75,000",
      "experience_level": "Mid-level",
      "latitude": 51.517637,
      "longitude": -0.074064
    },
    {
      "id": 10,
      "company": "Media Productions",
      "position": "Graphic Designer",
      "title": "Senior Graphic Designer",
      "description": "Create visually stunning graphics and artwork.",
      "type": "Full-time",
      "date_posted": "2023-09-23",
      "location": "Bangor",
      "postcode": "LL57 2SZ",
      "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
      "salary_range": "£60,000 - £80,000",
      "experience_level": "Senior",
    },
     
  
    {
      "id": 11,
      "company": "Tech Startups",
      "position": "Software Developer",
      "title": "Backend Developer",
      "description": "Develop server-side applications and APIs.",
      "type": "Full-time",
      "date_posted": "2023-09-24",
      "location": "Bangor",
      "postcode": "LL57 11MN",
      "skills_required": ["Python", "Django", "API Development"],
      "salary_range": "£50,000 - £70,000",
      "experience_level": "Mid-level",
    },
    {
      "id": 12,
      "company": "Marketing Masters",
      "position": "Marketing Manager",
      "title": "Digital Marketing Manager",
      "description": "Lead digital marketing campaigns.",
      "type": "Full-time",
      "date_posted": "2023-09-25",
      "location": "London",
      "postcode": "E1 8LJ",
      "skills_required": ["Digital Marketing", "SEO", "Social Media"],
      "salary_range": "£55,000 - £75,000",
      "experience_level": "Senior",
      "latitude": 51.509418,
      "longitude": -0.067649
    },
    {
      "id": 13,
      "company": "HealthTech Solutions",
      "position": "Healthcare IT Analyst",
      "title": "Clinical Systems Analyst",
      "description": "Analyze and improve healthcare IT systems.",
      "type": "Full-time",
      "date_posted": "2023-09-26",
      "location": "Bangor",
      "postcode": "LL57 13QR",
      "skills_required": ["Healthcare IT", "Data Analysis", "Electronic Health Records"],
      "salary_range": "$55,000 - $75,000",
      "experience_level": "Mid-level",
    },
    {
      "id": 14,
      "company": "GreenTech Innovations",
      "position": "Environmental Scientist",
      "title": "Environmental Researcher",
      "description": "Study environmental impact and sustainability.",
      "type": "Full-time",
      "date_posted": "2023-09-27",
      "location": "Bangor",
      "postcode": "LL57 2AB",
      "skills_required": ["Environmental Science", "Sustainability", "Climate Studies"],
      "salary_range": "£50,000 - £70,000",
      "experience_level": "Mid-level",
      "latitude": 53.227112,
      "longitude": -4.132689
    },
    {
      "id": 15,
      "company": "EduTech Solutions",
      "position": "Teacher",
      "title": "History Teacher",
      "description": "Inspire students with engaging history lessons.",
      "type": "Full-time",
      "date_posted": "2023-09-28",
      "location": "London",
      "postcode": "EC1A 1AA",
      "skills_required": ["Teaching", "History", "Curriculum Development"],
      "salary_range": "£80,000 - £100,000",
      "experience_level": "Mid-level",
      "latitude": 51.525136,
      "longitude": -0.111183
    },
    {
      "id": 16,
      "company": "EcoSolutions Ltd",
      "position": "Environmental Engineer",
      "title": "Environmental Consultant",
      "description": "Provide expertise in environmental conservation.",
      "type": "Full-time",
      "date_posted": "2023-09-29",
      "location": "Bangor",
      "postcode": "LL57 16WX",
      "skills_required": ["Environmental Consulting", "Conservation", "Ecosystem Analysis"],
      "salary_range": "£45,000 - £65,000",
      "experience_level": "Mid-level",
    },
    {
      "id": 17,
      "company": "Media Creations",
      "position": "Content Writer",
      "title": "Senior Content Writer",
      "description": "Create compelling written content for various platforms.",
      "type": "Full-time",
      "date_posted": "2023-09-30",
      "location": "Manchester",
      "postcode": "M1 3BD",
      "skills_required": ["Content Writing", "SEO", "Copywriting"],
      "salary_range": "£70,000 - £90,000",
      "experience_level": "Senior",
      "latitude": 53.476077,
      "longitude": -2.237711
    },
    {
      "id": 18,
      "company": "Tech Wizards",
      "position": "Software Engineer",
      "title": "Machine Learning Engineer",
      "description": "Develop machine learning models and algorithms.",
      "type": "Full-time",
      "date_posted": "2023-10-01",
      "location": "Bangor",
      "postcode": "LL57 3HG",
      "skills_required": ["Machine Learning", "Python", "Deep Learning"],
      "salary_range": "£80,000 - £100,000",
      "experience_level": "Senior",
      "latitude": 53.191209,
      "longitude": -4.058814
    },
    {
      "id": 19,
      "company": "Hospitality Group",
      "position": "Chef",
      "title": "Head Chef",
      "description": "Lead the culinary team in a high-end restaurant.",
      "type": "Full-time",
      "date_posted": "2023-10-02",
      "location": "Manchester",
      "postcode": "M1 5JB",
      "skills_required": ["Culinary Arts", "Menu Planning", "Kitchen Management"],
      "salary_range": "£50,000 - £70,000",
      "experience_level": "Senior",
      "latitude": 53.474581,
      "longitude": -2.248520
    },
    {
      "id": 20,
      "company": "Tech Innovators",
      "position": "Data Analyst",
      "title": "Data Scientist",
      "description": "Apply data science techniques to solve complex problems.",
      "type": "Full-time",
      "date_posted": "2023-10-03",
      "location": "London",
      "postcode": "EC2M 2AQ",
      "skills_required": ["Data Science", "Machine Learning", "Statistics"],
      "salary_range": "£55,000 - £75,000",
      "experience_level": "Senior",
      "latitude": 51.518872,
      "longitude": -0.086912
    },
  
  {
    "id": 21,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 2AE",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 53.228058,
    "longitude": -4.132533
  },
  {
    "id": 22,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 7AL",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level",
    "latitude": 53.472793,
    "longitude": -2.230220
  },
  {
    "id": 23,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW1A 1YT",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 51.481087,
      "longitude": -0.133947
  },
  {
    "id": 24,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH1 3TG",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 25,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3LE",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level",
    "latitude": 53.197978,
    "longitude": -4.063540
  },
  {
    "id": 26,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 27,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 7AU",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level",
    "latitude": 53.473631,
    "longitude": -2.238285
  },
  {
    "id": 28,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW1E 6AY",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 51.499738,
    "longitude": -0.140735
  },
  {
    "id": 29,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Glasgow",
    "postcode": "G2 1RW",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 30,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M4 3TR",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 31,
    "company": "TechNex Corp.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW19 3ES",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 51.498149,
    "longitude": -0.142601
  },
  {
    "id": 32,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 2AN",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level",
    "latitude": 53.228188,
    "longitude": -4.133303
  },
  {
    "id": 33,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Cambridge",
    "postcode": "CB3 0FD",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 34,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M11 2XZ",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level",
    "latitude": 53.475522,
    "longitude": -2.191349
  },
  {
    "id": 35,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 3BN",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 36,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 37,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3LU",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level",
    "latitude": 53.184515,
    "longitude": -4.071529
  },
  {
    "id": 38,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 7BJ",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.472494,
    "longitude": -2.236109
  },
  {
    "id": 39,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "CR0 2GN",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 51.383854,
    "longitude": -0.098495
  },
  {
    "id": 40,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3BZ",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level",
    "latitude": 53.173500,
    "longitude": -4.057636
  },
  {
    "id": 41,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bristol",
    "postcode": "BS1 6FU",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 42,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L3 1DL",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level"
  },
  {
    "id": 43,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "W8 5AU",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 51.501777,
    "longitude": -0.185487
  },
  {
    "id": 44,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH1 3TG",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 45,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3HN",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level",
    "latitude": 53.191127,
    "longitude": -4.058391
  },
  {
    "id": 46,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 47,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW1A 1AA",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 48,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 5DD",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.400298,
    "longitude": -2.980664
  },
  {
    "id": 49,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M12 5GW",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.466338,
    "longitude": -2.190419
  },
  {
    "id": 50,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 4ER",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level",
    "latitude": 53.169479,
    "longitude": -4.126867
  },
  {
    "id": 51,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bristol",
    "postcode": "BS1 6FU",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 52,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L3 1DL",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level"
  },
  {
    "id": 53,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 5DL",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.401782,
    "longitude": -2.984984
  },
  {
    "id": 54,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH1 3TG",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 55,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 3BN",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 56,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3EJ",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 53.191182,
    "longitude": -4.062586
  },
  {
    "id": 57,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M13 9ES",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level",
    "latitude": 53.466703,
    "longitude": -2.224254
  },
  {
    "id": 58,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH12 5DH",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 59,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 5EH",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.396885,
    "longitude": -2.978119
  },
  {
    "id": 60,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M4 3TR",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 61,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3NL",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 53.181959,
    "longitude": -4.064971
  },
  {
    "id": 62,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 7BP",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level",
    "latitude": 53.395428,
    "longitude": -2.973829
  },
  {
    "id": 63,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M7 4QU",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.512116,
    "longitude": -2.265794
  },
  {
    "id": 64,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH1 3TG",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 65,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 3BN",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 66,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 67,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 8JX",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level",
    "latitude": 53.401583,
    "longitude": -2.988334
  },
  {
    "id": 68,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 4HB",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.169543,
    "longitude": -4.125748
  },
  {
    "id": 69,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Glasgow",
    "postcode": "M15 6JN",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.464147,
    "longitude": -2.239000
    
  },
  {
    "id": 70,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 2YR",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level",
    "latitude": 53.222423,
    "longitude": -4.138919
  },
  {
    "id": 71,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M17 1GJ",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 53.469867,
    "longitude": -2.318529
  },
  {
    "id": 72,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 1NE",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level",
    "latitude": 53.407058,
    "longitude": -2.980548
  },
  {
    "id": 73,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 2NH",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.208111,
    "longitude": -4.166309
  },
  {
    "id": 74,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH1 3TG",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 75,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Liverpool",
    "postcode": "L1 1RG",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level",
    "latitude": 53.407149,
    "longitude": -2.982717
  },
  {
    "id": 76,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 77,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW1A 1AA",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 78,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Edinburgh",
    "postcode": "EH12 5DH",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 79,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M18 7BL",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.461409,
    "longitude": -2.180968
  },
  {
    "id": 80,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M4 3TR",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level"
  },
    
  
  {
    "id": 81,
    "company": "TechGenius Ltd.",
    "position": "Content Writer",
    "title": "Senior Copywriter",
    "description": "Create compelling content that resonates with our audience.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bristol",
    "postcode": "BS1 6FU",
    "skills_required": ["Content Writing", "Copywriting", "SEO"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 82,
    "company": "TechSupport Solutions",
    "position": "IT Support Specialist",
    "title": "Technical Support Engineer",
    "description": "Provide technical support to our users and resolve IT issues.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M18 8DJ",
    "skills_required": ["Technical Support", "Troubleshooting", "Customer Service"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Entry Level",
    "latitude": 53.467162,
    "longitude": -2.186069
  },
  {
    "id": 83,
    "company": "AI Innovations Ltd.",
    "position": "Software Engineer",
    "title": "AI Researcher",
    "description": "Conduct research in artificial intelligence and develop cutting-edge solutions.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Cambridge",
    "postcode": "CB3 0FD",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 84,
    "company": "DesignCrafters Inc.",
    "position": "Graphic Designer",
    "title": "Visual Design Specialist",
    "description": "Create visually appealing designs for various projects.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 2NT",
    "skills_required": ["Graphic Design", "Adobe Creative Suite", "Illustration"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level",
    "latitude": 53.205565,
    "longitude": -4.168861
  },
  {
    "id": 85,
    "company": "TechSolutions Ltd.",
    "position": "IT Project Manager",
    "title": "Project Lead",
    "description": "Lead IT projects and ensure successful project delivery.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M1 3BN",
    "skills_required": ["Project Management", "Agile", "Stakeholder Communication"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 86,
    "company": "Data Insights Ltd.",
    "position": "Data Analyst",
    "title": "Business Intelligence Analyst",
    "description": "Analyze data to provide insights for strategic decision-making.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Birmingham",
    "postcode": "B1 1BB",
    "skills_required": ["Data Analysis", "Business Intelligence", "SQL"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 87,
    "company": "CodeCrafters Inc.",
    "position": "Software Engineer",
    "title": "Frontend Developer",
    "description": "Join our frontend team to create responsive and engaging user interfaces.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "London",
    "postcode": "SW1A 1AA",
    "skills_required": ["JavaScript", "React", "HTML", "CSS"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 88,
    "company": "Brand Innovators Ltd.",
    "position": "Marketing Manager",
    "title": "Brand Marketing Director",
    "description": "Lead brand marketing initiatives and drive brand awareness.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M2 3AA",
    "skills_required": ["Brand Marketing", "Campaign Management", "Market Research"],
    "salary_range": "£70,000 - £90,000",
    "experience_level": "Senior Level",
    "latitude": 53.478008,
    "longitude": -2.242875
  },
  {
    "id": 89,
    "company": "InnovateTech Solutions",
    "position": "Software Engineer",
    "title": "Mobile App Developer",
    "description": "Develop innovative mobile applications for our users.",
    "type": "contract",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 3AB",
    "skills_required": ["Mobile App Development", "iOS", "Android", "Swift", "Kotlin"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.181672,
    "longitude": -4.065396
  },
  {
    "id": 90,
    "company": "PeopleFirst Inc.",
    "position": "HR Manager",
    "title": "People Operations Lead",
    "description": "Lead HR initiatives and foster a positive work environment.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Manchester",
    "postcode": "M4 3TR",
    "skills_required": ["HR Management", "Employee Relations", "Recruitment"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Senior Level"
  },
 
  {
    "id": 91,
    "company": "DataTech Innovations",
    "position": "Data Scientist",
    "title": "Machine Learning Engineer",
    "description": "Develop and deploy machine learning models for data analysis.",
    "type": "full-time",
    "date_posted": "2023-09-01",
    "location": "Manchester",
    "postcode": "M1 4DE",
    "skills_required": ["Machine Learning", "Python", "Data Analysis"],
    "salary_range": "£65,000 - £85,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 92,
    "company": "GreenEco Solutions",
    "position": "Environmental Scientist",
    "title": "Sustainability Analyst",
    "description": "Analyze and recommend sustainable practices for our projects.",
    "type": "contract",
    "date_posted": "2023-08-30",
    "location": "Birmingham",
    "postcode": "B5 4AJ",
    "skills_required": ["Environmental Science", "Sustainability", "Data Analysis"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    
  },
  {
    "id": 93,
    "company": "FinanceWise Ltd.",
    "position": "Financial Analyst",
    "title": "Investment Advisor",
    "description": "Provide financial advice and manage investment portfolios.",
    "type": "full-time",
    "date_posted": "2023-08-29",
    "location": "Manchester",
    "postcode": "M20 2AA",
    "skills_required": ["Financial Analysis", "Investment Management", "Finance"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level",
    "latitude": 53.416036,
    "longitude": -2.245035
  },
  {
    "id": 94,
    "company": "HealthPlus Innovations",
    "position": "Medical Doctor",
    "title": "Specialist Physician",
    "description": "Provide specialized medical care to patients in our healthcare facility.",
    "type": "full-time",
    "date_posted": "2023-08-28",
    "location": "Edinburgh",
    "postcode": "EH3 7JP",
    "skills_required": ["Medicine", "Clinical Expertise", "Patient Care"],
    "salary_range": "£80,000 - £100,000",
    "experience_level": "Senior Level"
  },
  {
    "id": 95,
    "company": "TechCrafters Inc.",
    "position": "Software Engineer",
    "title": "Backend Developer",
    "description": "Build and maintain scalable backend systems for our applications.",
    "type": "contract",
    "date_posted": "2023-08-27",
    "location": "Manchester",
    "postcode": "M20 2AU",
    "skills_required": ["Backend Development", "Java", "Database Management"],
    "salary_range": "£55,000 - £75,000",
    "experience_level": "Mid Level",
    "latitude": 53.410250,
    "longitude": -2.225821
  },
  {
    "id": 96,
    "company": "EduInnovate",
    "position": "Education Specialist",
    "title": "Curriculum Developer",
    "description": "Design and create engaging educational curricula for various subjects.",
    "type": "full-time",
    "date_posted": "2023-08-26",
    "location": "Cambridge",
    "postcode": "CB1 2QY",
    "skills_required": ["Curriculum Design", "Education", "Pedagogy"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 97,
    "company": "RoboTech Systems",
    "position": "Robotics Engineer",
    "title": "Automation Specialist",
    "description": "Design and implement robotic automation solutions for industrial processes.",
    "type": "contract",
    "date_posted": "2023-08-25",
    "location": "Manchester",
    "postcode": "M4 5JW",
    "skills_required": ["Robotics", "Automation", "Mechatronics"],
    "salary_range": "£60,000 - £80,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 98,
    "company": "TravelWave",
    "position": "Travel Consultant",
    "title": "Senior Travel Advisor",
    "description": "Plan and book travel experiences for our clients with attention to detail.",
    "type": "full-time",
    "date_posted": "2023-08-24",
    "location": "Bangor",
    "postcode": "LL57 4EZ",
    "skills_required": ["Travel Planning", "Customer Service", "Geographic Knowledge"],
    "salary_range": "£45,000 - £65,000",
    "experience_level": "Mid Level",
    "latitude": 53.207822,
    "longitude": -4.179701
  },
  {
    "id": 99,
    "company": "FoodEats",
    "position": "Chef",
    "title": "Head Chef",
    "description": "Lead culinary operations, create menus, and ensure high-quality dishes.",
    "type": "full-time",
    "date_posted": "2023-08-23",
    "location": "Edinburgh",
    "postcode": "EH12 6JD",
    "skills_required": ["Culinary Arts", "Menu Planning", "Kitchen Management"],
    "salary_range": "£40,000 - £60,000",
    "experience_level": "Mid Level"
  },
  {
    "id": 100,
    "company": "MediaFusion",
    "position": "Media Producer",
    "title": "Video Content Creator",
    "description": "Produce engaging video content for digital and broadcast platforms.",
    "type": "contract",
    "date_posted": "2023-08-22",
    "location": "Manchester",
    "postcode": "M20 2BN",
    "skills_required": ["Video Production", "Editing", "Storytelling"],
    "salary_range": "£50,000 - £70,000",
    "experience_level": "Mid Level",
    "latitude": 53.411799,
    "longitude": -2.229049
  },

  
  
  
  
  

  


  
  
  
  
  
  
  
  
  
    
  
]

export default jobs;
